openapi: 3.1.1

info:
  title: API Horaires
  summary: API du service de gestion des horaires
  description: |
    Cette API gère la programmation des films du cinéma. Elle fournit des endpoints pour créer, 
    lire et supprimer des entrées d'horaires. Chaque entrée d'horaire associe une date avec une liste 
    de films diffusés à cette date. Ce service est utilisé par le service Booking pour valider 
    que les films sont disponibles aux dates demandées.
  contact:
    name: Clovis SFEIR 
    url: https://etrange.org/
    email: clovis.sfeir@imt-atlantique.net
  version: 1.0.0

tags:
  - name: horaires
    description: Opérations liées à la programmation des films

paths:
  /:
    get:
      tags:
        - horaires
      summary: page d'accueil du service
      operationId: home
      description: Page de bienvenue du service Horaires
      responses:
        '200':
          description: message de bienvenue
          content:
            text/html:
              schema:
                type: string
                example: "<h1 style='color:blue'>Bienvenue dans le service Horaires!</h1>"

  /schedule:
    get:
      tags:
        - horaires
      summary: obtenir tous les horaires
      operationId: get_all_schedules
      description: Récupère la programmation complète avec toutes les dates et films
      responses:
        '200':
          description: liste de toutes les entrées d'horaires
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ScheduleItem'
    
    post:
      tags:
        - horaires
      summary: ajouter un film à la programmation
      operationId: add_movie_to_schedule
      description: Ajoute une nouvelle projection de film à la programmation
      requestBody:
        description: Entrée d'horaire à ajouter
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleItem'
      responses:
        '201':
          description: film ajouté à la programmation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Film ajouté à l'horaire
                  data:
                    $ref: '#/components/schemas/ScheduleItem'
        '400':
          description: champs requis manquants
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: film déjà programmé à cette date/heure
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /schedule/{date}:
    get:
      tags:
        - horaires
      summary: obtenir les horaires pour une date spécifique
      operationId: get_schedule_by_date
      description: Récupère tous les films programmés pour une date donnée
      parameters:
        - name: date
          in: path
          required: true
          description: Date au format AAAAMMJJ
          schema:
            type: string
            example: "20151130"
      responses:
        '200':
          description: horaires pour la date
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ScheduleItem'
        '404':
          description: aucun horaire trouvé pour cette date
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /schedule/movie/{movieid}:
    get:
      tags:
        - horaires
      summary: obtenir toutes les dates pour un film
      operationId: get_schedule_by_movie
      description: Récupère toutes les dates programmées pour un film spécifique
      parameters:
        - name: movieid
          in: path
          required: true
          description: ID du film
          schema:
            type: string
            example: 720d006c-3a57-4b6a-b18f-9b713b073f3c
      responses:
        '200':
          description: entrées d'horaires pour le film
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ScheduleItem'
        '404':
          description: aucun horaire trouvé pour ce film
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /schedule/{movieid}/{date}:
    get:
      tags:
        - horaires
      summary: vérifier si un film est programmé à une date
      operationId: check_movie_schedule
      description: Vérifie si un film spécifique est disponible à une date donnée (utilisé par le service Booking)
      parameters:
        - name: movieid
          in: path
          required: true
          description: ID du film
          schema:
            type: string
            example: 720d006c-3a57-4b6a-b18f-9b713b073f3c
        - name: date
          in: path
          required: true
          description: Date au format AAAAMMJJ
          schema:
            type: string
            example: "20151130"
      responses:
        '200':
          description: le film est programmé à cette date
          content:
            application/json:
              schema:
                type: object
                properties:
                  date:
                    type: string
                    example: "20151130"
                  movieid:
                    type: string
                    example: 720d006c-3a57-4b6a-b18f-9b713b073f3c
                  available:
                    type: boolean
                    example: true
        '404':
          description: film non programmé à cette date
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    delete:
      tags:
        - horaires
      summary: supprimer une entrée d'horaire spécifique
      operationId: delete_schedule
      description: Supprime un film de la programmation pour une date spécifique
      parameters:
        - name: movieid
          in: path
          required: true
          description: ID du film
          schema:
            type: string
            example: 720d006c-3a57-4b6a-b18f-9b713b073f3c
        - name: date
          in: path
          required: true
          description: Date au format AAAAMMJJ
          schema:
            type: string
            example: "20151130"
      responses:
        '200':
          description: entrée d'horaire supprimée
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Horaire supprimé avec succès
        '404':
          description: entrée d'horaire non trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /schedule/date/{date}:
    delete:
      tags:
        - horaires
      summary: supprimer tous les horaires pour une date
      operationId: delete_all_schedules_for_date
      description: Supprime tous les films programmés pour une date spécifique
      parameters:
        - name: date
          in: path
          required: true
          description: Date au format AAAAMMJJ
          schema:
            type: string
            example: "20151130"
      responses:
        '200':
          description: tous les horaires supprimés pour la date
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Tous les horaires du 20151130 ont été supprimés
        '404':
          description: aucun horaire trouvé pour cette date
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    ScheduleItem:
      type: object
      required:
        - date
        - movies
      properties:
        date:
          type: string
          example: "20151130"
          description: Date au format AAAAMMJJ
        movies:
          type: array
          items:
            type: string
          example: ["720d006c-3a57-4b6a-b18f-9b713b073f3c", "a8034f44-aee4-44cf-b32c-74cf452aaaae"]
          description: Liste des ID de films diffusés à cette date
    
    Error:
      type: object
      properties:
        error:
          type: string
          example: Aucun horaire trouvé pour cette date
